---
Author: Endre Kulcsár
Version: 155 17-CNL 113 761, Rev. A
Date: 2012-12-12

---
= BSSMAP (11.2.0) Protocol Modules for TTCN-3 Toolset with TITAN, Function Specification
:author: Endre Kulcsár
:revnumber: 155 17-CNL 113 761, Rev. A
:revdate: 2012-12-12
:toc:


== How to Read This Document

This is the Function Specification for the set of BSSMAP (v11.2.0) protocol modules. BSSMAP protocol modules are developed for the TTCN-3 Toolset with TITAN.

== Scope

The purpose of this document is to specify the content of the BSSMAP (V11.2.0) protocol modules.

= General

Protocol modules implement the message structures of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language <<_2, [2]>> and correctly encoding/decoding messages when executing test suites using the TITAN TTCN-3 test environment.

Protocol modules are using TITAN’s RAW encoding attributes <<_3, [3]>> and hence are usable with the TITAN test toolset only.

= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the BSSMAP protocol, version 11.2.0 (see <<_1, [1]>>).

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All BSSMAP messages listed in section 3.2 of <<_1, [1]>> are implemented, except for the ones listed in <<protocol-modifications-deviations, Protocol Modifications/Deviations>>

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

The following messages are not implemented:

* EMERGENCY RESET INDICATION

* EMERGENCY RESET COMMAND

Message type definitions for these messages are missing from <<_1, [1]>>.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name |Type of formal parameters |Type of return value
|`enc_PDU_BSSAP` |PDU_BSSAP |octetstring
|`dec_PDU_BSSAP` |octetstring |PDU_BSSAP
|`enc_PDU_BSSAP_fast` |PDU_BSSAP |octetstring
|`dec_PDU_BSSAP_backtrack` |octetstring |PDU_BSSAP
|===

== Limitations

Debug log generation is not supported when this revision of this product is used with TITAN version R7A (1.7pl0), because the encoder/decoder functions, automatically generated by TITAN version R7A (1.7pl0) do not contain logging functions. Newer versions of TITAN supports the debug logging within the automatically generated encoder/decoder functions that can be activated by allowing the `DEBUG_ENCDEC` (see Programmer's Technical Reference for TITAN TTCN-3 Test Executor, clause 6.2.3.2) in TITAN runtime configuration files.

= Terminology

TITAN TTCN-3 Test Executor (see <<_3, [3]>>).

= Abbreviations

3GPP:: 3rd Generation Partnership Project

BSSAP:: Base Station Subsystem Application Part

BSSMAP:: Base Station Subsystem Management Application Part

TTCN-3:: Testing and Test Control Notation version 3

= References

[[_1]]
[1] 3GPP TS 48.008 V11.2.0 (2012-05) +
3rd Generation Partnership Project; +
Technical Specification Group GSM/EDGE Radio Access Network; +
Mobile Switching Centre - Base Station System(MSC-BSS) interface; +
Layer 3 specification(Release 11)

[[_2]]
[2] ETSI ES 201 873-1 v4.4.1 (2012-04) +
The Testing and Test Control Notation version 3; Part 1: Core Language

[[_3]]
[3] TITAN User Guide

